name: ci

on:
  pull_request:
  push:
    branches:
      - 'master'


jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       R: [ '4.0.5', '4.1.3' ]
  #   name: R ${{ matrix.R }} test
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup R
  #       uses: r-lib/actions/setup-r@v2
  #       with:
  #         r-version: ${{ matrix.R }}
  #     - uses: r-lib/actions/setup-r-dependencies@v2
  #       with:
  #         extra-packages: any::rcmdcheck
  #         needs: check
  #     - uses: r-lib/actions/check-r-package@v2
  #       with:
  #         args: 'c("--no-manual")'
  #         error-on: '"error"'
  #         check-dir: '"check"'

  docker_build:
    # needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: sagebionetworks/cleanad:latest


  docker_push:
    needs: [docker_build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: sagebionetworks/cleanad:latest
